<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Health & AI</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <style>
    :root {
      --sidebar: #1F6F78;
      --bg: #F6F7F3;
      --card: #FFFFFF;
      --text-main: #1E2A2A;
      --text-muted: #6F7F7D;
      --checkins: #D6EFE6;
      --reminder: #E6B450;
      --sos: #C62828;
    }

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: Arial, sans-serif;
    }

    body {
      display: flex;
      min-height: 100vh;
      background: var(--bg);
      flex-direction: row;
    }

    /* ===== SIDEBAR ===== */
    .sidebar {
      width: 240px;
      background: var(--sidebar);
      color: #fff;
      display: flex;
      flex-direction: column;
      transition: transform 0.3s ease;
    }

    .sidebar h2 {
      padding: 20px;
      text-align: center;
      border-bottom: 1px solid rgba(255,255,255,0.2);
    }

    .nav-btn {
      padding: 14px 20px;
      text-decoration: none;
      color: #fff;
      font-size: 14px;
      display: block;
    }

    .nav-btn:hover,
    .nav-btn.active {
      background: rgba(255,255,255,0.15);
    }

    .logout {
      margin-top: auto;
      background: var(--sos);
      text-align: center;
    }

    /* ===== CONTENT ===== */
    .content {
      flex: 1;
      padding: 20px;
      overflow-x: auto;
    }

    h1 {
      color: var(--text-main);
      margin-bottom: 15px;
    }

    /* ===== CARDS ===== */
    .cards {
      display: flex;
      flex-wrap: wrap;
      gap: 15px;
      margin-bottom: 20px;
    }

    .card {
      flex: 1 1 200px;
      background: var(--card);
      padding: 15px;
      border-radius: 10px;
      box-shadow: 0 4px 10px rgba(0,0,0,0.08);
      min-width: 150px;
      text-align: center;
    }

    .card h2 {
      font-size: 18px;
      color: var(--text-main);
      margin-bottom: 5px;
    }

    .card p {
      color: var(--text-muted);
      font-size: 14px;
    }

    /* ===== TABLE ===== */
    .table-card {
      background: var(--card);
      padding: 15px;
      border-radius: 10px;
      box-shadow: 0 4px 10px rgba(0,0,0,0.08);
      overflow-x: auto;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      min-width: 500px;
    }

    th, td {
      padding: 12px;
      border-bottom: 1px solid #ddd;
      text-align: left;
      color: var(--text-main);
      font-size: 14px;
    }

    th {
      background: var(--checkins);
    }

    .actions button {
      padding: 6px 12px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 12px;
      background: var(--checkins);
    }

    /* ===== RESPONSIVE ===== */
    @media screen and (max-width: 768px) {
      body {
        flex-direction: column;
      }
      .sidebar {
        width: 100%;
        flex-direction: row;
        overflow-x: auto;
      }
      .sidebar h2 {
        flex: 1 0 auto;
      }
      .nav-btn {
        flex: 1 0 auto;
        text-align: center;
      }
      .content {
        padding: 15px;
      }
      table {
        min-width: 400px;
      }
    }
  </style>
</head>

<body>

  <!-- SIDEBAR -->
  <div class="sidebar">
    <h2>Admin Panel</h2>

    <a class="nav-btn" href="Dashboard.php">Dashboard</a>
    <a class="nav-btn" href="Caregivers.php">Caregivers</a>
    <a class="nav-btn" href="Elders.php">Elders</a>
    <a class="nav-btn" href="CaregiverLinks.php">Caregiver Links</a>
    <a class="nav-btn active" href="HealthAI.php">Health & AI</a>
    <a class="nav-btn" href="Reminders.php">Reminders</a>
    <a class="nav-btn" href="SOS.php">SOS & Emergency</a>
    <a class="nav-btn" href="Messages.php">Messages</a>
    <a class="nav-btn" href="Location.php">Location</a>

    <a class="nav-btn logout" href="Login.php">Logout</a>
  </div>

  <!-- CONTENT -->
  <div class="content">
    <h1>Health & AI</h1>

    <!-- KPIs / Cards -->
    <div class="cards">
      <div class="card">
        <h2>Average Health Score</h2>
        <p>78%</p>
      </div>
      <div class="card">
        <h2>AI Suggestions</h2>
        <p>5 alerts today</p>
      </div>
      <div class="card">
        <h2>Critical Alerts</h2>
        <p>2 elders</p>
      </div>
    </div>

    <!-- Table of AI Alerts -->
    <div class="table-card">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Elder Name</th>
            <th>Alert Type</th>
            <th>Generated By</th>
            <th>Severity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Sunil Perera</td>
            <td>Medication Missed</td>
            <td>AI System</td>
            <td style="color: var(--sos)">High</td>
            <td class="actions"><button class="view">View</button></td>
          </tr>
          <tr>
            <td>2</td>
            <td>Mary Fernando</td>
            <td>Low Activity</td>
            <td>AI System</td>
            <td style="color: var(--reminder)">Medium</td>
            <td class="actions"><button class="view">View</button></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

</body>
</html>
